locations:
  - {name: T1, dir: N, sleep: 3}
  - {name: C1, dir: N, sleep: 3}
  - {name: S2, dir: N, sleep: 3}
  - {name: S4, dir: N, sleep: 3}
  - {name: S3, dir: N, sleep: 3}
  - {name: T2, dir: N, sleep: 3}
  - {name: S1, dir: N, sleep: 3}
  - {name: S5, dir: N, sleep: 3}
  - {name: T4, dir: N, sleep: 3}
  - {name: T3, dir: N, sleep: 3}
  - {name: D2, dir: N, sleep: 3}
  - {name: D1, dir: N, sleep: 3}
  - {name: T1, dir: E, sleep: 3}
  - {name: C1, dir: E, sleep: 3}
  - {name: S2, dir: E, sleep: 3}
  - {name: S4, dir: E, sleep: 3}
  - {name: S3, dir: E, sleep: 3}
  - {name: T2, dir: E, sleep: 3}
  - {name: S1, dir: E, sleep: 3}
  - {name: S5, dir: E, sleep: 3}
  - {name: T4, dir: E, sleep: 3}
  - {name: T3, dir: E, sleep: 3}
  - {name: D2, dir: E, sleep: 3}
  - {name: D1, dir: E, sleep: 3}
  - {name: T1, dir: S, sleep: 3}
  - {name: C1, dir: S, sleep: 3}
  - {name: S2, dir: S, sleep: 3}
  - {name: S4, dir: S, sleep: 3}
  - {name: S3, dir: S, sleep: 3}
  - {name: T2, dir: S, sleep: 3}
  - {name: S1, dir: S, sleep: 3}
  - {name: S5, dir: S, sleep: 3}
  - {name: T4, dir: S, sleep: 3}
  - {name: T3, dir: S, sleep: 3}
  - {name: D2, dir: S, sleep: 3}
  - {name: D1, dir: S, sleep: 3}
  - {name: T1, dir: W, sleep: 3}
  - {name: C1, dir: W, sleep: 3}
  - {name: S2, dir: W, sleep: 3}
  - {name: S4, dir: W, sleep: 3}
  - {name: S3, dir: W, sleep: 3}
  - {name: T2, dir: W, sleep: 3}
  - {name: S1, dir: W, sleep: 3}
  - {name: S5, dir: W, sleep: 3}
  - {name: T4, dir: W, sleep: 3}
  - {name: T3, dir: W, sleep: 3}
  - {name: D2, dir: W, sleep: 3}
  - {name: D1, dir: W, sleep: 3}
